- .circleci/config.yml
* `./performanceTest.wls` currently fails on CI because the fix to it was not ported from *SetReplace*.
* This disables that test entirely since it is currently empty anyway.
> Disable performance test on CI

- Tests/PostTagSystemFinalState.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagMultihistory.cpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Changes the phase conventions in Post's system so that phase `1` is now phase `2`, and phase `2` is now phase `1`.
* Changes both `PostTagSystem` and `PostTagSystemFinalState` implementations.
* ***Warning***: phases are now different. Sorry for potential headache: phases are being changes by *Stephen Wolfram*'s request:
```wl
In[] := PostTagSystemFinalState[{0, {0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0}}, 20858040]
Out[] = {2, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/3)
> Change phase conventions

- Kernel/GeneratePostTagSystemHistory.m
- Kernel/PostTagSystemFinalState.m
- Kernel/cpp.m
- Tests/GeneratePostTagSystemHistory.wlt
- Tests/PostTagSystemFinalState.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/WolframLanguageAPI.cpp
- libPostTagSystem/WolframLanguageAPI.hpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Adds GeneratePostTagSystemHistory function that returns an association with evaluation results, including `"EventCount"` and `"FinalState"`.
* This makes it easier to use the evaluation function because one can tell whether the requested event count ran or not.
* Obtain the number of events produced in an evolution:
```wl
In[] := GeneratePostTagSystemHistory[{0, {0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0}}, 10^9]
Out[] = <|"EventCount" -> 20858048, "FinalState" -> {0, {0, 0, 0, 0, 0, 0, 0}}|>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/4)
> GeneratePostTagSystemHistory with event count

- .circleci/config.yml
* Fixes CMake link in CI on macOS to use a specific version as it got broken with the latest release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/6)
> Fix macOS CMake to a specific version

- Kernel/GeneratePostTagSystemHistory.m
- Kernel/cpp.m
- Tests/GeneratePostTagSystemHistory.wlt
- Tests/PostTagSystemFinalState.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/WolframLanguageAPI.cpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Implements checkpoints to `GeneratePostTagSystemHistory` and `PostTagSystemFinalState`.
* Allows one to specify states which, if reach, should stop the evolution.
* The next step would be generating these checkpoints at runtime at exponentially-increasing event numbers, which would allow one to detect arbitrary cycles in O(n log(n)).
* Note that only states after 8n events will be detected. Intermediate states will be missed.
* I did not test the effect on performance yet, but it should not be significant, as (1) in no checkpoints case, it just adds an empty for-loop to the bit-packed evolution code, and (2) checkpoint comparison is done on bit-packed states and terminates immediately in case of any mismatch.
* Terminate the Post Tag System early once a checkpoint is reached also …
> Checkpoints

- .circleci/config.yml
* CMake download was broken. This PR fixes it to a specific version (like in *SetReplace*) so that it keeps working in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/8)
> Fix Windows CMake to specific version

- Kernel/GeneratePostTagSystemHistory.m
- Kernel/GenerateTagSystemHistory.m
- Kernel/cpp.m
- Tests/GeneratePostTagSystemHistory.wlt
- Tests/GenerateTagSystemHistory.wlt
- Tests/PostTagSystemFinalState.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/WolframLanguageAPI.cpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Implements packed system 002211.
* Unpacking will be implemented in a separate PR.
* The tape cells in system 002211 can take states `0`, `1` and `2`, that is, they need 2 bits to encode them not one.
* As a result, it's packed a bit sparser, and, in particular, one can do 4 events at a time instead of 8 like in the "Post" system.
* Evaluate system "002211":
```wl
In[] := GenerateTagSystemHistory[
"002211", {0, {0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0}}, 660]
Out[] = <|"EventCount" -> 660, "FinalState" -> {1, {0, 0, 1, 0, 0, 1, 0, 0}}|>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/7)
> System 002211

- Kernel/packing.m
- Tests/packing.wlt
* Implements `ToPackedTagSystemState` and `FromPackedTagSystemState` functions.
* They convert the tag system states between the unpacked NKS representation, and the bit-packed representation that is used internally in the package.
* Pack a state:
```wl
In[] := ToPackedTagSystemState["002211"][{0, 0, 1, 1, 2, 2, 2, 1, 0, 2}]
Out[] = {0, {0, 0, 0, 1, 1, 0, 1, 0, 0, 0}}
```
* Unpack it back:
```wl
In[] := FromPackedTagSystemState["002211"][{0, {0, 0, 0, 1, 1, 0, 1, 0, 0, 0}}]
Out[] = {0, _, 1, _, 2, _, 2, _, 0, _}
```
* Note that some cells are missing. That is because their values are not required and will be skipped by the evaluator. `ToPackedTagSystemState` accepts the states with blanks assuming the blanks are at correct positions:
```wl
In[] := ToPackedTagSystemState["002211"][{0, _, …
```
> Packing and unpacking

- Kernel/GenerateTagSystemHistory.m
- Kernel/packing.m
- Tests/GenerateTagSystemHistory.wlt
- Tests/packing.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
* Adds implementation of `{{0, 0} -> {0}, {1, 0} -> {1, 0, 1}, {0, 1} -> {0, 0, 0}, {1, 1} -> {0, 1, 1}}` (system 000010111).
* Unlike previous rules, it reads multiple non-aligned digits from the tape at once.
* Reproduce the evolution of a terminating system:
```wl
In[] := GenerateTagSystemHistory["000010111", {0, IntegerDigits[716, 2, 10]}, 10^9]
Out[] = <|"EventCount" -> 100280, "FinalState" -> {0, {0, 0, 0, 0, 0, 0}}|>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/10)
> System 000010111

- Kernel/GenerateTagSystemHistory.m
- Kernel/cpp.m
- Tests/GeneratePostTagSystemHistory.wlt
- Tests/GenerateTagSystemHistory.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/WolframLanguageAPI.cpp
* Adds `"MaxTapeLength"` to the output association produced by `Generate(Post)TagSystemHistory`.
* This keep tracks of the length of the tape, and returns the maximum encountered during the evolution.
Note, the tape length is computed for the compressed binary representation while running the bit-packed algorithm. That means:
* Superfluous values are ignored (i.e., the values that would not be used in the input). So, the lengths in the original system would be multiplied by the phase count.
* If the system has more than two tape states, the `"MaxTapeLength"` will be larger because it needs to get converted to the binary representation. So, it needs to be divided by `Ceiling[Log2[tapeStateCount]]`.
* Since the tape is evaluated `8 / tapeStateCount` steps at-a-time, the intermediate tape …
> MaxTapeLength

- Kernel/GenerateTagSystemHistory.m
- Kernel/cpp.m
- Tests/GenerateTagSystemHistory.wlt
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/WolframLanguageAPI.cpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Allows one to specify a special value `"PowerOfTwoEventCounts"` as a checkpoint.
* This will automatically create checkpoints at 0, 1, 2, 4, 8, ..., 2^k, ... events.
* Assuming that Post tag system always terminates or reaches a cycle, this will guarantee that `GenerateTagSystemHistory` will always terminate even if the number of events is very large (infinity).
* Consider a system that ends with a cycle (so, does not terminate):
```wl
In[] := GenerateTagSystemHistory["Post", {2, {0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0}}, 1024, {}]
Out[] = <|"EventCount" -> 1024,
"MaxTapeLength" -> 13,
"FinalState" -> {1, {1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1}}|>
```
* One can now automatically evaluate it until the cycle is reached. The following creates the checkpoints at events 0, 1, 2, 4, 8, 16, 32 and …
> PowerOfTwoEventCounts checkpoints

- lint.sh
* Removes Markdown and bash linting from `lint.sh`.
* The correct solution would be to add flags to disable/enable them (or, better yet, only lint modified files in the hook), however, that solution should be implemented in *SetReplace* instead (and then copied here). This PR is just a quick fix for the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/15)
> Remove Markdown and bash formatting from lint.sh

- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/WolframLanguageAPI.cpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
- libPostTagSystem/test/PostTagSystem_test.cpp
* Allows one to terminate the evolution once the max tape length is reached.
* `PostTagSearcher` can now use `maxTapeLength` parameters as well.
* Evaluate a state up to tape length of 52:
```c++
PostTagHistory::EvaluationLimits limits;
limits.maxTapeLength = 52;
const auto& result =
PostTagHistory().evaluate(PostTagHistory::NamedRule::Post, TagState(20, 123, 0), limits);
```
* This returns the evolution result:
```prose
conclusionReason           MaxTapeLengthExceeded
finalState
tape	                   54 bits
headState	           1
eventCount	           912
maxIntermediateTapeLength  54
```
* Note that the final tape length exceeds the constraint because it terminates on the first 8-step the constraint is exceeded.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> Max tape length limit

- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
* `PostTagSearcher` now uses explicit checkpoints from `EvaluationParameters`.
* The trie from explicit checkpoints is only constructed once and shared across all inputs.
* There is a separate trie for automatic checkpoints which is unique to each input.
* We might want to share the automatic checkpoints trie in the future as well, but that will require storing checkpoints source in the trie itself (to distinguish between `"ReachedCycle"` and `"MergedWithAnotherInput"`) conclusions.
* The following produces 6 outputs, in which 0th and 3rd reach the provided checkpoint:
```c++
PostTagSearcher::EvaluationParameters parameters;
parameters.checkpoints = {{{0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0}, 2}};
const auto result = PostTagSearcher().evaluateRange(20, 123, 125, parameters);
```
---
This …
> Searcher checkpoints

- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/PostTagSearcher.hpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
* `PostTagSearcher` now correctly uses the time constraint parameter.
* `ConclusionReason` will either be `TimeConstraintExceeded` or `NotEvaluated` based on whether the time constraint was reached before or during the evaluation of a particular init.
* Checkpoints #21 should be merged first.
* The time constraint will be exceeded slightly because results need to be collected.
* The first result of the following concludes with reason `TimeConstraintExceeded`:
```c++
PostTagSearcher::EvaluationParameters parameters;
parameters.groupTimeConstraintNs = 100000000;  // 0.1 seconds
const auto result = PostTagSearcher().evaluateRange(
64, 1473593303835332608, 1473593303835332609, parameters);
```
* The other two results are `NotEvaluated` for now, but that can change after parallelization is …
> Time constraint

- libPostTagSystem/CheckpointsTrie.cpp
- libPostTagSystem/CheckpointsTrie.hpp
- libPostTagSystem/PostTagHistory.cpp
- libPostTagSystem/PostTagHistory.hpp
- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/PostTagSearcher.hpp
- libPostTagSystem/test/CheckpointsTrie_test.cpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
* Use shared trie for a range evaluation.
* This uses more memory but saves a lot of time because the same evaluation paths ("highways") don't need to be evaluated multiple times.
* To accommodate this case, `MergedWithAnotherInit` was added as a `ConclusionReason`.
* There is currently no way to find out which other init this one was merged into. This potentially can be added, but it will require a change in the file format, so I did not add it now.
* A better approach might be to make this optimization invisible by automatically figuring out the values of all evaluation result components based on the information about the merge. I can work on this approach now, but I'm not sure I can finish it today (so it might have to wait until next week).
* The difference in performance can be seen …
> Shared trie

- FileFormats/README.md
- FileFormats/ResultFile.wl
* Add MergedWithAnotherInit to ResultFile WL importer and result file format documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/26)
> Update conclusion reasons

- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/PostTagSearcher.hpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
* Add an EvaluationParameters option to include/exclude inits that merged with another init (set to exclude by default)
* It turns out that in large scale computations ~99.9% of inits end up with this conclusion reason (which is good; it means the shared trie is very effective). These are of limited scientific interest, and discarding them massively reduces the size of output files.
* We may eventually want a generic mechanism for choosing the conclusion reasons to keep/discard. This could then be exposed on the command line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/25)
> Excluding merged inits

- libPostTagSystem/PostTagSearcher.cpp
- libPostTagSystem/test/PostTagSearcher_test.cpp
* Resolves #27.
* `uint64_t` `tapeEnd` was converted incorrectly to `TagState` `tapeEnd` due to `uint64_t` value exceeding `tapeLength` and becoming a zero as a result.
* Consequently, `evaluateRange` would never terminate as it will be generating new inits to infinity (the for-loop has a `state != end` stopping condition which is never reached).
* The `tapeLength` is now increased in this situation.
* The example from the issue now evaluates instantly as expected:
```console
$ ./wolfram-postproject --chase --initstart 1073741823 --initcount 1 --initsize 30
Maximum tape size: 1e+09
Maximum step count: 1e+10
Total evaluation time limit: unlimited
No crib file specified; not loading checkpoints
Evaluating 1 initial condition tapes, starting at 1073741823...
----------------
Evaluation …
```
> Fix last tape

- DevUtils/BuildLibPostTagSystem.m
* Fixes just-in-time compilation which was broken on macOS.
* Package is now compiled currently on `Get`:
```wl
Get["~/git/PostTagSystem/Kernel/init.m"];
In[] := GenerateTagSystemHistory[
"Post", {0, {1, 1, 1, 1, 1, 1, 1, 1, 1, 1}}, 1000000, {"PowerOfTwoEventCounts"}]
Out[] = <|
"EventCount" -> 4120, "MaxTapeLength" -> 69, "FinalState" -> {0, {0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0}}|>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maxitg/posttagsystem/29)
> Fix macOS just-in-time compilation
